config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :sessions
  resources :questions
  resources :answers
  resources :comments, only: [:new, :create, :destroy]
  resources :tags

  post 'vote_question' => 'questions#vote'
  post 'vote_answer' => 'answers#vote'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :tag_string, :tag_list

  belongs_to :user

  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
  has_many :question_tags
  has_many :tags, through: :question_tags

  validates :title, :body, :user, presence: true

  def set_tags(tag_string)
    tag_string.split(",").each do |tag_name|
      tag_str = tag_name.downcase.chomp.strip
      self.tags << Tag.find_or_create_by(name: tag_str) unless self.tags.any? { |tag_obj| tag_obj.name == tag_str }
    end
  end

  def tag_string
    @tag_string
  end

  def tags_as_string
    self.tags.map { |tag| tag.name }.join(", ")
  end


  def vote_count
    self.votes.map {|vote| vote.value}.reduce(:+).to_s
  end

  def write_comment_count
    self.comments.count.to_s
  end

  def write_user_name
    self.user.username
  end

  def write_date
    Kronic.format(self.created_at)
  end

  def is_owned_by(current_user)
    current_user == self.user
  end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

 skip_before_action :logged_in?, only: [:index, :show]
 include VotesHelper

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params.merge(user: current_user))
    if @question.save
      @question.set_tags(@question.tag_string)
      redirect_to question_path(@question)
    else
      flash[:notice] = "You need to fill out both fields. Please try again"
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    redirect_to "/" unless @question.is_owned_by(current_user)
    if @question.update_attributes(question_params)
      @question.set_tags(@question.tag_string)
      redirect_to question_path
    else
      flash[:notice] = "Please try again"
      redirect_to edit_question_path
    end
  end

  def show
    @question = Question.find(params[:id])
    @comments = @question.comments
  end

  def index
    @questions = sort_by_votes(Question.all)
  end

  def vote
    vote = check_vote(vote_params)
    if vote.save
      redirect_to question_path(params[:vote][:question])
    else

      flash[:notice] =  "Sorry, your vote doesn't count"
      redirect_to question_path(params[:vote][:question])
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :tag_string)
  end

  def vote_params
    params.require(:vote).permit(:value).merge(user: current_user, voteable_id: params[:vote][:question], voteable_type: "Question")
  end

  def sort_by_votes(collection)
    collection.sort_by { |obj| obj.vote_count }.reverse
  end


end

app/helpers/questions_helper.rb
module QuestionsHelper

end

app/views/questions/_question.html.erb
<section>
  <h3><%= link_to question.title, question_path(question) %><span class="right light small"><%= question.vote_count %> Votes | <%= question.write_comment_count %> comments</span></h3>
  <P class="light small"><%= question.write_date %> by <%= link_to question.write_user_name, user_path(question.user) %> </P>
   <p><%= render question.tags %></p>
</section>

app/views/questions/edit.html.erb
<%= form_for @question do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.label :tag_string, "Tags" %>
      <%= f.text_field :tag_string, value: @question.tags_as_string %>
    </div>


    <div>
      <%= f.submit "Make Changes" %>
    </div>
<% end %>

app/views/questions/index.html.erb
<h1>Questions!</h1> <%= link_to "Add Question", new_question_path, class: "button" %>
<%= render @questions %>

app/views/questions/new.html.erb
<%= form_for @question, url: {action: 'create'} do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.label :tag_string %>
      <%= f.text_field :tag_string %>
    </div>


    <div>
      <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/questions/show.html.erb
<% if @question.is_owned_by(current_user) %>
  <%= link_to "Edit", edit_question_path, class: "button" %>
<% end %>
<section>
  <div class="question-body">
    <%= link_to "UP", vote_question_path(vote: {value: 1, question: @question}), method: :post %>
    <%= link_to "DOWN", vote_question_path(vote: {value: -1, question: @question}), method: :post %>
    <h3><%= @question.title %><span class="right light small"><%= @question.vote_count %> Votes | <%= @question.write_comment_count %> comments</span></h3>
    <P class="light"><%= @question.write_date %> by <%= link_to @question.write_user_name, user_path(@question.user) %>  </P>
    <p class="row"><%= @question.body %></p>
    <p><%= render @question.tags %></p>
  </div>
  <div>
    <p class="add-comment-link"><%= link_to "Add comment", {controller:"comments", action:"new", question: @question}%></p>
    <%= render @comments %>
  </div>
</section>

<h2>Answers:</h2>
<%= render @question.answers  %>

<% if current_user %>
<section>
  <%= render partial: 'answers/new'  %>
</section>
<% end %>