config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :sessions
  resources :questions
  resources :answers
  resources :comments, only: [:new, :create, :destroy]
  resources :tags

  post 'vote_question' => 'questions#vote'
  post 'vote_answer' => 'answers#vote'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  has_many :votes, as: :voteable
  has_many :comments, as: :commentable


  validates :body, :user, :question, presence: true


  def vote_count
    self.votes.map {|vote| vote.value}.reduce(:+).to_s
  end

  def write_comment_count
    self.comments.count.to_s
  end

  def write_user_name
    self.user.username
  end

  def write_date
    Kronic.format(self.created_at)
  end

  def is_owned_by(current_user)
    current_user == self.user
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, :user, presence: true

  def writer
    self.user.username
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :tag_string, :tag_list

  belongs_to :user

  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
  has_many :question_tags
  has_many :tags, through: :question_tags

  validates :title, :body, :user, presence: true

  def set_tags(tag_string)
    tag_string.split(",").each do |tag_name|
      tag_str = tag_name.downcase.chomp.strip
      self.tags << Tag.find_or_create_by(name: tag_str) unless self.tags.any? { |tag_obj| tag_obj.name == tag_str }
    end
  end

  def tag_string
    @tag_string
  end

  def tags_as_string
    self.tags.map { |tag| tag.name }.join(", ")
  end


  def vote_count
    self.votes.map {|vote| vote.value}.reduce(:+).to_s
  end

  def write_comment_count
    self.comments.count.to_s
  end

  def write_user_name
    self.user.username
  end

  def write_date
    Kronic.format(self.created_at)
  end

  def is_owned_by(current_user)
    current_user == self.user
  end



end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag

  validates :question, :tag, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :question_tags
  has_many :questions, through: :question_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

  validates :email, presence: true, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :username, presence: true


end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include VotesHelper
  def new
    @question = Question.find(parms[:id])
  end

  def create
    answer = Answer.new(body: params[:answers][:body], user: current_user, question_id: params[:answers][:question_id])
    if answer.save
      redirect_to question_path(answer.question)
    else
      flash[:notice] = "Something went wrong saving your answer."
      # render 'answers/show'
    end
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def edit
    question = Question.find(params[:id])
  end

  def update
    answer = Answer.find(params[:answer][:answer_id])
    if answer.user == current_user
      answer.update(answer_params)
      answer.body.to_json
      # format.json { render json: answer.body}
    else
      flash[:notice] = "You cannot update any one else's answers..."
    end
  end

  def destroy
  end

  def vote
   vote = check_vote(vote_params)
    if vote.save
      redirect_to :back
    else

      flash[:notice] =  "Sorry, your vote doesn't count"
      redirect_to :back
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:value).merge(user: current_user, voteable_id: params[:vote][:answer], voteable_type: "Answer")
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    if params[:question]
      @question = Question.find_by(id: params[:question])
    elsif params[:answer]
      @answer = Answer.find_by(id: params[:answer])
    end
  end

  def create
    @question = Question.find_by(id: params[:comment][:question_id])
    @answer = Answer.find_by(id: params[:comment][:answer_id])
    @comment = Comment.new(comment_params)
    if @question
      if @comment.save
        flash[:notice] = "Comment created"
        redirect_to question_path(@question)
      else
        flash[:notice] = "Invalid Comment"
        redirect_to question_path(@question)
      end
    elsif @answer
      if @comment.save
        flash[:notice] = "Comment created"
        redirect_to question_path(@answer.question.id)
      else
        flash[:notice] = "Invalid Comment"
        redirect_to question_path(@answer.question.id)
      end
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    if current_user == @comment.user
      @comment.destroy
      redirect_to :back
    else 
      flash[:notice] = "You cannot delete another's comment."
      redirect_to :back
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type).merge(user:current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in?, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Please check your login information and try again"
      redirect_to new_session_path
    end
  end

  def destroy
    session.clear
    redirect_to "/"
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
    @tag = Tag.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :logged_in?, only: [:new, :create]

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(current_user)
    else
      flash[:notice] = "There was a problem with your information, please try again"
      render new_user_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      flash[:notice] = "There was a problem"
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :description, :password )
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

   skip_before_action :logged_in?, only: [:index]

  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def vote_count
    self.votes.map {|vote| vote.value}.reduce(:+).to_s
  end

  def write_comment_count
    self.comments.count.to_s
  end

  def write_user_name
    self.user.username
  end

  def write_date
    Kronic.format(self.created_at)
  end

  def is_owned_by(current_user)
    current_user == self.user
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper

  def check_vote(vote_params)
    if vote = Vote.find_by(vote_params.except(:value))
      vote.assign_attributes(vote_params)
      vote
    else
      Vote.new(vote_params)
    end

  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_answer.html.erb
<section class="answers">
  <p class="small light">Written by: <%= link_to answer.user.username, user_path(answer.user) %>

    <span class="right"><%= link_to image_tag("up.png", size: '20x20'), vote_answer_path(vote: {value: 1, answer: answer}), method: :post, class: "up" %>

      <%= link_to image_tag("down.png", size: '20x28'), vote_answer_path(vote: {value: -1, answer: answer}), method: :post %>
      <%= answer.vote_count %> Votes | <%= answer.write_comment_count %> comments</span>


    <p class="small light" id="edit-answer-link">
      <% if answer.is_owned_by(current_user) %>
        <%= link_to "Edit Answer", edit_answer_path, question: 'test' %>
      <% end %>
    </p>

  </p>

  <% if answer.is_owned_by(current_user) %>
    <section id="answer"><%= answer.body %></section>

    <section id="edit-answer">
      <%= render partial: 'answers/edit', locals: {answer: answer} %>
    </section>

  <% else %>
    <section><%= answer.body %></section>
  <% end %>



  <br />

    <p class="light">
      <%= link_to "Create comment", {controller:"comments", action:"new", answer: answer} %>
    </p>
    <%= render answer.comments %>
</section>

app/views/answers/_edit.html.erb
<%= form_for answer, remote: true, url: {action: :update, controller: :answers},:html => {:class => "answer-edit-form"} do |f| %>
      <%= f.hidden_field :question_id, value: @question.id %>
      <%= f.hidden_field :answer_id, value: answer.id %>
      <%= f.text_area :body %>

    <div>
      <%= f.submit 'Update answer' %>
    </div>
<% end %>

app/views/answers/_new.html.erb
<%= form_for :answers, url: {action: :create, controller: :answers} do |f| %>
    <div>
      <%= f.hidden_field :question_id, value: @question.id %>
      <%= f.label :name, "Your answer" %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.submit 'submit' %>
    </div>
<% end %>

app/views/answers/_show.html.erb
<%= answer.body %>

app/views/answers/_show.json.erb
<%= answer.body %>

app/views/comments/_comment.html.erb
<div class="comment">
  <p><%= comment.body %></p>
  <p class="small light">By: <%=  link_to comment.writer, user_path(comment.writer)%></p>
  <% if current_user == comment.user %>
	 <span class="light small"><%= link_to "Delete this comment", comment, method: :delete, data: {confirm: "Are you sure you want to delete this comment?"} %></span>
  <% end %>
</div>

app/views/comments/_new.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <% if @question %>
    <%= f.hidden_field :commentable_id, value: @question.id %>
    <%= f.hidden_field :commentable_type, value: 'Question' %>
  <% elsif @answer %>
    <%= f.hidden_field :commentable_id, value: @answer.id %>
    <%= f.hidden_field :commentable_type, value: 'Answer' %>
  <% end %>
  <%= submit_tag "Write comment" %>
<% end %>

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <% if @question %>
    <%= f.hidden_field :commentable_id, value: @question.id %>
    <%= f.hidden_field :question_id, value: @question.id %>
    <%= f.hidden_field :commentable_type, value: 'Question' %>
  <% elsif @answer %>
    <%= f.hidden_field :commentable_id, value: @answer.id %>
    <%= f.hidden_field :answer_id, value: @answer.id %>
    <%= f.hidden_field :commentable_type, value: 'Answer' %>
  <% end %>
  <%= submit_tag "Write comment" %>
<% end %>

app/views/tags/_tag.html.erb
<div class="tag">
  <%= link_to tag.name, tag_path(tag) %>
</div>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h3>Questions tagged with "<%= @tag.name %>"" </h3>
<%= render @tag.questions %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>


    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>


    <div>
      <%= f.submit "Save Changes" %>
    </div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: 'create'} do |f| %>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>


    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>


    <div>
      <%= f.submit "Register" %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1>Hey <%= @user.username %></h1>
<h3>Your questions: </h3>
<%= render @user.questions %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/update.html.erb
<h1>Votes#update</h1>
<p>Find me in app/views/votes/update.html.erb</p>